language: python
python:
    - "2.7"
env:
    - DJANGO=django==1.7.7
    - DJANGO=django==1.8
before_install:
    - sudo apt-get install imagemagick
install:
    - pip install $DJANGO
    - pip install -r requirements.txt
script: ./testrunner.py
